---

- name: Copy in the memcached collectd config
  copy: src=memcached.conf dest=/etc/collectd.d/memcached.conf
  tags:
  - collectd/memcached
  - collectd
  - memcached
  notify: restart collectd

- name: lastly, set some selinux booleans
  seboolean: name=collectd_tcp_network_connect persistent=yes state=yes
  tags:
  - collectd/memcached
  - collectd
  - memcached
  - selinux
