
- name: Setup arm-packager hosts
  hosts: arm-packager
  user: root
  gather_facts: True
  tags:
   - arm-packager

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"

  roles:
  - base
  - rkhunter
  - hosts
  - fas_client
  - sudo

  tasks:
  # this is how you include other task lists
  - import_tasks: "{{ tasks_path }}/motd.yml"

  - name: install packager tools (dnf)
    dnf: state=present pkg={{ item }}
    with_items:
    - fedora-packager
    when: ansible_distribution_major_version|int > 21
    tags:
    - packages

  - name: allow packagers to use mock
    lineinfile: dest=/etc/pam.d/mock line="{{ item }} sufficient pam_succeed_if.so user ingroup packager use_uid quiet" insertbefore=BOF
    with_items:
    - account
    - auth
    tags:
    - config

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
