# create a new backup server system
# NOTE: should be used with --limit most of the time
# NOTE: make sure there is room/space for this instance on the buildvmhost
# NOTE: most of these vars_path come from group_vars/backup_server or from hostvars

---
- name: Make backup server system
  hosts: backup
  user: root
  gather_facts: true

  vars_files:
    - /srv/web/infra/ansible/vars/global.yml
    - "/srv/private/ansible/vars.yml"
    - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - hosts
  - openvpn/client
  - ipa/client
  - sudo
  - collectd/base
  - { role: nfs/client,
      mnt_dir: '/fedora_backups',
      nfs_mount_opts: "rw,hard,bg,intr,noatime,nodev,nosuid,sec=sys,nfsvers=3",
      nfs_src_dir: 'fedora_backups' }
  - role: grokmirror_mirror
  - role: weblate-backup
  - {role: linux-system-roles.nbde_client, tags: ['nbde_client']}
  - serial-console

  pre_tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"

  tasks:
  - import_tasks: "{{ tasks_path }}/rdiff_backup_server.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
