#- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=bastion"

- name: make the boxen be real for real
  hosts: bastion
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios/client
  - hosts
  - fas_client
  - sudo
  - collectd/base
  - { role: openvpn/server, when: not inventory_hostname.startswith('bastion-comm01') }
  - { role: packager_alias, when: not inventory_hostname.startswith('bastion-comm01') }

  tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

- name: configure bastion-qa
  hosts: bastion-qa
  user: root
  gather_facts: True

  tasks:
  - name: install needed packages
    yum: pkg={{ item }} state=present
    with_items:
    - ipmitool
