- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=bodhi2:bodhi2-stg"

- name: make the box be real
  hosts: bodhi2:bodhi2-stg
  user: root
  gather_facts: True

  vars_files:
  - /srv/web/infra/ansible/vars/global.yml
  - "/srv/private/ansible/vars.yml"
  - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios/client
  - hosts
  - fas_client
  - sudo
  - collectd/base
  - rsyncd
  - apache
  - { role: bodhi2/base, when: "inventory_hostname.startswith('bodhi0')" }
  - { role: fedmsg/base,  when: "inventory_hostname.startswith('bodhi0')" }

  tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"
  - import_tasks: "{{ tasks_path }}/mod_wsgi.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
