- import_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=certgetter"

- name: make the box be real
  hosts: certgetter
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - hosts
  - fas_client
  - rsyncd
  - sudo
  - apache
  - { role: openvpn/client,
      when: env != "staging" }

  pre_tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"

  tasks:
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

  - name: make sure certbot is installed
    package: name=certbot state=installed

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
