---
- name: Setup copr hypervisor hosts
  hosts: copr_hypervisor
  user: root
  gather_facts: true

  vars_files:
  - /srv/web/infra/ansible/vars/global.yml
  - "{{ private }}/vars.yml"
  - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:
    - include_role: name=copr/reboot
      tags: always
    - import_tasks: "{{ tasks_path }}/yumrepos.yml"

  tasks:
    - import_role: name=base
    - import_role: name=hosts
    - import_role: name=rkhunter
    - import_role: name=nagios_client
    - import_role: name=openvpn/client
    - import_role: name=ipa/client
    - import_role: name=copr/hypervisor

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
