# create a new mirrorlist server
# NOTE: should be used with --limit most of the time
# NOTE: make sure there is room/space for this server on the vmhost
# NOTE: most of these vars_path come from group_vars/mirrorlist or from hostvars

#- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=mirrorlist2:mirrorlist2-stg"

- name: make the box be real
  hosts: mirrorlist2:mirrorlist2-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:
  - name: global default packages to install (yum)
    yum: state=present name={{ item }}
    with_items:
    - wget
    - epel-release
    - libselinux-python
    tags:
    - packages
    - base
  - include: "{{ tasks }}/yumrepos.yml"
  - include: "{{ tasks }}/mod_wsgi.yml"
  - name: Install policycoreutils-python
    yum: pkg=policycoreutils-python state=present

  - name: Create /srv/web/ for all the goodies.
    file: >
        dest=/srv/web state=directory
        owner=root group=root mode=0755
    tags:
    - httpd
    - httpd/website


  - debug: msg="{{ansible_nodename}}  {{inventory_hostname}} {{ansible_distribution_major_version|int}}"

  tasks:
  # this is how you include other task lists
  - include: "{{ tasks }}/motd.yml"

  roles:
  - hosts
  - apache
  - mirrormanager/mirrorlist2

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
