- import_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=nagios:nagios-stg"

- name: make the box be real
  hosts: nagios:nagios-stg
  user: root
  gather_facts: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios/client
  - hosts
  - fas_client
  - collectd/base
  - { role: rsyncd, when: datacenter == 'online' }
  - sudo
  - { role: openvpn/client,
      when: env != "staging" }
  - apache

  tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"
  - import_tasks: "{{ tasks_path }}/mod_wsgi.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

- name: deploy service-specific config (just for production)
  hosts: nagios
  user: root
  gather_facts: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
   - "/srv/web/infra/ansible/vars/nagios.{{ inventory_hostname_short }}.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

  roles:
  - { role: dhcp_server, when: datacenter == 'online' }
  - { role: tftp_server, when: datacenter == 'online' }
  - nagios/server
  - fedmsg/base
