- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=pkgs-stg:pkgs02.rpmfusion.org"

- name: make the box be real
  hosts: pkgs-stg:pkgs01.online.rpmfusion.net
  user: root
  gather_facts: True

  vars_files:
  - /srv/web/infra/ansible/vars/global.yml
  - "/srv/private/ansible/vars.yml"
  - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios/client
  - fas_client
  - collectd/base
  - sudo
  - apache
  - gitolite/base
  - cgit/base
  - cgit/clean_lock_cron
  - cgit/make_pkgs_list
  - gitolite/check_fedmsg_hooks
  - git/make_checkout_seed
  - git/server
  - git/hooks
  - clamav
  - { role: nfs/client, when: env != "staging", mnt_dir: '/srv/cache/lookaside',  nfs_src_dir: 'rpmfusion_sourcecache', nfs_mount_opts='rw,hard,bg,intr,noatime,nodev,nosuid,nfsvers=3' }
  - role: distgit
    tags: distgit

  tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

# setup minimal proxy includes
- include: /srv/web/infra/ansible/playbooks/include/proxies-certificates.yml
- include: /srv/web/infra/ansible/playbooks/include/proxies-websites.yml
- include: /srv/web/infra/ansible/playbooks/include/proxies-reverseproxy.yml
- include: /srv/web/infra/ansible/playbooks/include/proxies-rewrites.yml
- include: /srv/web/infra/ansible/playbooks/include/proxies-redirects.yml
- include: /srv/web/infra/ansible/playbooks/include/proxies-fedora-web.yml

- name: setup fedmsg on pkgs
  hosts: pkgs-stg:pkgs01.online.rpmfusion.net
  user: root
  gather_facts: True

  vars_files:
  - /srv/web/infra/ansible/vars/global.yml
  - "/srv/private/ansible/vars.yml"
  - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - { role: collectd/fedmsg-service, process: fedmsg-hub }
  - fedmsg/base
  - fedmsg/hub

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
