# create a new database server system
# NOTE: should be used with --limit most of the time
# NOTE: most of these vars_path come from group_vars/backup_server or from hostvars

- import_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=db02.online.rpmfusion.net"

# Once the instance exists, configure it. 

- name: configure postgresql server system
  hosts: db02.online.rpmfusion.net
  user: root
  gather_facts: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - fas_client
  - nagios/client
  - hosts
  - postgresql_server
  - collectd/base
  - collectd/postgres  # This requires a 'databases' var to be set in host_vars
  - sudo
  - koji_db

  tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

# TODO: add iscsi task

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
