---
# Configuration for the pkgdb2 webapp

- name: install needed packages
  yum: pkg={{ item }} state=present
  with_items:
  - pkgdb2
  - python-psycopg2
  - python-openid-cla
  - python-openid-teams
  - python-flask-openid
  - python-memcached
  - libsemanage-python
  - pyliblzma
  - python-bunch
  tags:
  - packages
  - pkgdb

- name: install the project logo
  copy: src={{ files }}/common/logo.png dest=/usr/lib/python2.7/site-packages/pkgdb2/static/packagedb-logo.png owner=root mode=644
  tags:
  - config
  - pkgdb

- name: copy sundry pkgdb configuration
  template: src={{ item.file }}
            dest={{ item.location }}/{{ item.dest }}
            owner=apache group=apache mode=0600
  with_items:
  - { file: pkgdb2_admin.cfg, location: /etc/pkgdb2, dest: pkgdb2.cfg }
  - { file: alembic.ini, location: /etc/pkgdb2, dest: alembic.ini }
  changed_when: "1 != 1"
  tags:
  - config
  - pkgdb
  notify:
  - restart apache

- name: create the database scheme
  command: /usr/bin/python2 /usr/share/pkgdb2/pkgdb2_createdb.py
  changed_when: "1 != 1"
  environment:
      PKGDB2_CONFIG: /etc/pkgdb2/pkgdb2.cfg
  tags: pkgdb

- name: Install all the configuration file of pkgdb2
  template: src={{ item.file }}
            dest={{ item.location }}/{{ item.file }}
            owner=apache group=apache mode=0600
  with_items:
  - { file: pkgdb2.cfg, location: /etc/pkgdb2 }
  - { file: pkgdb2.conf, location: /etc/httpd/conf.d }
  - { file: pkgdb2.wsgi, location: /var/www/, dest: pkgdb2.wsgi }
  tags:
  - config
  - pkgdb
  notify:
  - restart apache

- name: Install the pkgdb cron jobs - sync bugzilla, update pkg info
  when: inventory_hostname.startswith('pkgdb02')
  template: src={{ item.file }}
            dest={{ item.location }}/{{ item.file }}
  with_items:
  - { file: 'pkgdb-sync-bugzilla.cron', location: /etc/cron.d }
  - { file: 'pkgdb_update_package_info.cron', location: /etc/cron.d }
  tags:
  - config
  - pkgdb


- name: set sebooleans so pkgdb2 can talk to the db
  seboolean: name=httpd_can_network_connect_db
                    state=true
                    persistent=true
  tags:
  - selinux
  - pkgdb

- name: set sebooleans so apache can send emails
  seboolean: name=httpd_can_sendmail
                    state=true
                    persistent=true
  tags:
  - selinux
  - pkgdb

- name: set sebooleans so apache can talk to memcached0*
  seboolean: name=httpd_can_network_memcache
                    state=true
                    persistent=true
  tags:
  - selinux
  - pkgdb
