#!/bin/sh

source /root/sshagent >>/dev/null

TMPDIR=`mktemp -d /tmp/backups.XXXX`

cd $TMPDIR
git clone ssh://git.rpmfusion.org/git/infrastructure/ansible 
ansible-playbook -i ansible/inventory ansible/playbooks/rdiff-backup.yml 
