- name: Copy some config files for {{website}}
  copy: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - fedora-web.conf
  - languages.conf
  - cache.conf
  - persona.conf
  - hotspot.conf
  - expires.conf
  - deflate.conf
  notify:
  - reload httpd
  tags:
  - fedora-web
  - fedora-web/main
  - fedora-web/hotspot

- name: And one template (for {{website}})
  template: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - sponsor.conf
  notify:
  - reload httpd
  when: sponsor is defined
  tags:
  - fedora-web
  - fedora-web/main

- name: Create a file for hotspot
  copy: dest=/srv/web/hotspot.txt content="OK"
        owner=root group=root mode=0644
        setype=httpd_sys_content_t
  tags:
  - fedora-web
  - fedora-web/main
  - fedora-web/hotspot

- name: And, copy over a template for browserid
  template: >
    src=browserid.rpmfusion.org dest=/srv/web/browserid.rpmfusion.org
    owner=root group=root mode=0644
  notify:
  - reload httpd
  tags:
  - fedora-web
  - fedora-web/main

# TODO -- turn these into redirects in playbooks/groups/proxies-redirect.yml
- name: Copy over some miscellaneous redirects (for stg)
  copy: >
    src=redirects.conf.stg dest=/etc/httpd/conf.d/{{website}}/redirects.conf
    owner=root group=root mode=0644
  when: env == "staging"
  notify:
  - reload httpd
  tags:
  - fedora-web
  - fedora-web/main

# TODO -- turn these into redirects in playbooks/groups/proxies-redirect.yml
- name: Copy over some miscellaneous redirects (for prod) 
  copy: >
    src=redirects.conf.prod dest=/etc/httpd/conf.d/{{website}}/redirects.conf
    owner=root group=root mode=0644
  when: env != "staging"
  notify:
  - reload httpd
  tags:
  - fedora-web
  - fedora-web/main
