---
- name: install pam_url
  package: name=pam_url state=present
  tags:
  - packages
  when: ansible_distribution_major_version|int < 22

- name: install pam_url
  dnf: name=pam_url state=present
  tags:
  - packages
  when: ansible_distribution_major_version|int > 21

- name: /etc/pki/tls/private/totpcgi.pem
  copy: src="{{ private }}/files/2fa-certs/keys/{{ inventory_hostname }}.pem" dest=/etc/pki/tls/private/totpcgi.pem mode=0400
  tags:
  - config
  when: ansible_distribution == 'DISABLED'

- name: /etc/pki/tls/private/totpcgi-ca.cert
  copy: src="{{ private }}/files/2fa-certs/keys/ca.crt" dest=/etc/pki/tls/private/totpcgi-ca.cert mode=0400
  tags:
  - config
  when: ansible_distribution == 'DISABLED'



