#
# This task creates a swap file
#


- name: create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs={{ swap_file_bs }} count={{ swap_file_count }}
  args:
    creates: "{{ swap_file_path }}"

- name: Check swap file permission
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600

- name: Check swap file type
  command: file {{ swap_file_path }}
  check_mode: no
  register: swapfile

- name: Make swap file
  command: mkswap {{ swap_file_path }}
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  when: ansible_swaptotal_mb < 1
