---
- name: Install postfix
  ansible.builtin.package: name=postfix state=present
  tags:
  - postfix
  - packages

- name: /etc/postfix/main.cf
  ansible.builtin.copy: src={{ item }} dest=/etc/postfix/main.cf
  with_first_found:
    - "{{ postfix_maincf }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ ansible_fqdn }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ inventory_hostname }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ host_group }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ postfix_group }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf.{{ datacenter }}"
    - "{{ roles_path }}/base/files/postfix/main.cf/main.cf"
  notify:
  - Restart postfix
  tags:
  - postfix
  - config

- name: Enable postfix to start
  service: name=postfix state=started enabled=true
  tags:
  - service
