---
# tasklist for setting up a rdiff backup server.
- name: Install rdiff-backup
  ansible.builtin.package: name={{ item }} state=present
  with_items:
  - rdiff-backup
  - git
  - ansible
  tags:
  - packages

- name: Setup rdiff backup script
  ansible.builtin.copy: src="{{ files }}/rdiff-backup/run-rdiff-backups" dest=/usr/local/bin/run-rdiff-backups mode=755
  tags:
  - config

- name: Setup rdiff backup cron
  ansible.builtin.copy: src="{{ files }}/rdiff-backup/run-rdiff-backups.cron" dest=/etc/cron.d/run-rdiff-backups
  tags:
  - config
