---
# collectd server setup

# install pkg
- name: install collectd server packages
  package: name={{ item }} state=present
  with_items:
  - collectd-rrdtool
  - collectd-ping
  - collectd-web
  - collectd-rabbitmq-data
  notify:
  - restart collectd
  tags:
  - config
  - collectd/server

# install collectd ping config
- name: install collectd ping config
  copy: src=ping.conf dest=/etc/collectd.d/ping.conf
  notify:
  - restart collectd
  tags:
  - config
  - collectd/server

# install collectd rrd config
- name: install collectd rrd config
  copy: src=rrdtool.conf dest=/etc/collectd.d/rrdtool.conf
  notify:
  - restart collectd
  tags:
  - config
  - collectd/server

# install apache config
- name: install collectd apache config
  copy: src=collectd.conf dest=/etc/httpd/conf.d/collectd.conf
  tags:
  - config
  - collectd/server

# install upgrade target
- name: install collect upgrade target to handle v4 clients
  copy: src=vfive-upgrade.conf dest=/etc/collectd.d/vfive-upgrade.conf
  tags:
  - config
  - collectd/server

# create /var/log/collectd as it's on a larger volume
- name: create /var/log/collectd
  file: path=/var/log/collectd owner=root group=root mode=0755 state=directory
  tags:
  - config
  - collectd/server

# create a link from /var/lib/collectd to /var/log/collectd
- name: create link from /var/lib/collectd to /var/log/collectd
  file: state=link src=/var/log/collectd dest=/var/lib/collectd
  tags:
  - config
  - collectd/server

# push our custom config file for the graph CGIs
- name: push the collection.conf file
  copy:
    src: collection.conf
    dest: /etc/collection.conf
  tags:
  - config
  - collectd/server
