---
# tasks file for opendkim

- name: install needed packages for opendkim
  yum: pkg={{ item }} state=present
  with_items:
  - opendkim
  tags:
  - opendkim
  - packages

- name: install the default keys
