---
# tasks file for bugzilla
#
- name: Install needed packages for bugzilla
  ansible.builtin.package:
    state: present
    name:
    - bugzilla
    - bugzilla-contrib
    - perl-Encode-Detect
    - perl-Test-Taint
    - perl-XMLRPC-Lite
  tags:
  - packages
  - bugzilla

- name: Install perl-DBD-MySQL if needed by bugzilla
  ansible.builtin.package:
    state: present
    name: perl-DBD-MySQL
  when: bugzilla_db_driver == 'MySQL'
  tags:
  - packages
  - bugzilla

- name: Install perl-DBD-Pg if needed by bugzilla
  ansible.builtin.package:
    state: present
    name: perl-DBD-Pg
  when: bugzilla_db_driver == 'Pg'
  tags:
  - packages
  - bugzilla

- name: Bugzilla localconfig in place
  ansible.builtin.template: src=localconfig dest=/etc/bugzilla/localconfig mode=0640 owner=root group=apache
  tags:
  - config
  - bugzilla

- name: Install apache httpd bugzilla
  ansible.builtin.copy: src="bugzilla-httpd.conf" dest="/etc/httpd/conf.d/bugzilla.conf" owner=root group=root
  tags:
  - config

