---
# tasks file for bugzilla
#
- name: install eseyman bugzilla 4.4 copr repo
  copy: src="eseyman-bugzilla-4.4-epel-7.repo" dest="/etc/yum.repos.d/eseyman-bugzilla-4.4-epel-7.repo" owner=root group=root
  tags:
  - config
  - packages
  - yumrepos

- name: install needed packages for bugzilla
  yum: pkg={{ item }} state=present
  with_items:
  - bugzilla
  - bugzilla-contrib
  - perl-Encode-Detect
  - perl-Test-Taint
  - perl-XMLRPC-Lite
  tags:
  - packages
  - bugzilla

- name: install perl-DBD-MySQL if needed by bugzilla
  yum: pkg=perl-DBD-MySQL state=present
  when: bugzilla_db_driver == 'MySQL'
  tags:
  - packages
  - bugzilla

- name: install perl-DBD-Pg if needed by bugzilla
  yum: pkg=perl-DBD-Pg state=present
  when: bugzilla_db_driver == 'Pg'
  tags:
  - packages
  - bugzilla

- name: bugzilla localconfig in place
  template: src=localconfig dest=/etc/bugzilla/localconfig mode=0640 owner=root group=apache
  tags:
  - config
  - bugzilla


