---
# tasks file for bugzilla
#
- name: install eseyman bugzilla 5.0 copr repo
  copy: src="eseyman-bugzilla-5.0-epel-7.repo" dest="/etc/yum.repos.d/bugzilla-epel.repo" owner=root group=root
  tags:
  - config
  - packages
  - yumrepos
  when: ansible_distribution_major_version|int == 7

- name: install needed packages for bugzilla
  yum: pkg={{ item }} state=present
  with_items:
  - bugzilla
  - bugzilla-contrib
  - perl-Encode-Detect
  - perl-Test-Taint
  - perl-XMLRPC-Lite
  tags:
  - packages
  - bugzilla

- name: install perl-DBD-MySQL if needed by bugzilla
  yum: pkg=perl-DBD-MySQL state=present
  when: bugzilla_db_driver == 'MySQL'
  tags:
  - packages
  - bugzilla

- name: install perl-DBD-Pg if needed by bugzilla
  yum: pkg=perl-DBD-Pg state=present
  when: bugzilla_db_driver == 'Pg'
  tags:
  - packages
  - bugzilla

- name: bugzilla localconfig in place
  template: src=localconfig dest=/etc/bugzilla/localconfig mode=0640 owner=root group=apache
  tags:
  - config
  - bugzilla

- name: install apache httpd bugzilla
  copy: src="bugzilla-httpd.conf" dest="/etc/httpd/conf.d/bugzilla.conf" owner=root group=root
  tags:
  - config

