- name: Install sigul bridge
  yum: state=present name=sigul-bridge
  tags:
  - packages

- name: Setup sigul bridge.conf
  template: src=bridge.conf.j2 dest=/etc/sigul/bridge.conf
            owner=sigul group=sigul mode=0640
  tags:
  - config

- name: Setup primary koji config file
  copy: src=koji-primary.conf dest=/etc/koji-primary.conf owner=root group=root mode=644

