- name: install chrony
  package: name=chrony state=present
  tags:
  - chrony
  - package
  - base

- name: install chrony.conf
  template: src=chrony.conf.j2 dest=/etc/chrony.conf
  tags:
  - chrony
  - config
  - base

- name: Start and enable chrony
  service: name=chronyd state=started enabled=yes
  tags:
  - chrony
  - service
  - base
