- name: handle ssh keys on a hosts birthday (new hw machine)
  hosts: "{{ myhosts }}"
  gather_facts: False

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  tasks:
  - import_tasks: "{{ tasks_path }}/happy_birthday.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

