- name: Set up some domain rewrites.
  hosts: proxies-stg:proxies
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

  roles:

  - role: httpd/domainrewrite
    destname: admin
    website: admin.rpmfusion.org
    target: https://admin.rpmfusion.org/account

  - role: httpd/domainrewrite
    destname: apache-status
    website: admin.rpmfusion.org
    path: /status

