#! /bin/sh

rootpath="/srv/web/infra/ansible/playbooks"
parallel=8 # limit since ansible-playbook takes O(1GB) RAM each on batcave

find $rootpath/hosts $rootpath/groups -type f -name '*.yml' |
   xargs -I'{}' -P $parallel ansible-playbook '{}' --check --diff
