#!/bin/bash

#
# A simple script to copy database dumps over to public space on batcave01
# Only the most recent dump is published
#
scp db02:/backups/koji-$(date +%F).dump.xz /srv/web/infra/db-dumps/koji.dump.xz
scp db02:/backups/pkgdb2-$(date +%F).dump.xz /srv/web/infra/db-dumps/pkgdb2.dump.xz
scp db02:/backups/bodhi2-$(date +%F).dump.xz /srv/web/infra/db-dumps/bodhi2.dump.xz
scp db02:/backups/fas2-$(date +%F).dump.xz /srv/web/infra/db-dumps/fas2.dump.xz
