# restricted to run on cloud instances only
- hosts: 209.132.184.*
  user: root
  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
  
  tasks:
  - import_tasks: "{{ tasks_path }}/cloud_setup_basic.yml"


  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
