- name: make a new ssl ticketkey
  hosts: hv01.online.rpmfusion.net
  user: root

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

  tasks:
  - name: create new production ticket key
    command: dd if=/dev/random of=/root/ticketkey_production.tkey bs=1 count=48

  - name: create new staging ticket key
    command: dd if=/dev/random of=/root/ticketkey_staging.tkey bs=1 count=48

- name: Push out new ticket key
  hosts: proxies:proxies-stg
  user: root

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

  tasks:

  - name: deploy ticket key
    copy: src=/root/ticketkey_{{env}}.tkey dest=/etc/httpd/ticketkey_{{env}}.tkey
          owner=root group=root mode=0600
    notify:
    - reload httpd
