# create a new qadevel server
#
# This server looks for rawhide builds and requests they be signed. 
#

- name: make qadevel server
  hosts: qadevel;qadevel-stg
  user: root
  gather_facts: False

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  tasks:
  - import_tasks: "{{ tasks_path }}/virt_instance_create.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

- name: make the box be real
  hosts: qadevel;qadevel-stg
  user: root
  gather_facts: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - fas_client
  - collectd/base
  - sudo

  tasks:
  - import_tasks: "{{ tasks_path }}/hosts.yml"
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
